# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Song.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Song.proto',
  package='micromusic',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nSong.proto\x12\nmicromusic\"0\n\x04Song\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\tb\x06proto3')
)




_SONG = _descriptor.Descriptor(
  name='Song',
  full_name='micromusic.Song',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='micromusic.Song.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='micromusic.Song.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='micromusic.Song.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['Song'] = _SONG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Song = _reflection.GeneratedProtocolMessageType('Song', (_message.Message,), dict(
  DESCRIPTOR = _SONG,
  __module__ = 'Song_pb2'
  # @@protoc_insertion_point(class_scope:micromusic.Song)
  ))
_sym_db.RegisterMessage(Song)


# @@protoc_insertion_point(module_scope)
